name: IPWhitelist
version: '${project.version}'
main: dev.rohrjaspi.ipwhitelist.Main
api-version: '1.20'

commands:
  ipwhitelist:
    permission: ip.commands.add
    aliases:
      - ipw
      - whitlistip

